# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-version
  namespace: default
  labels:
    app: print-version
spec:
  selector:
    matchLabels:
      app: print-version
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: print-version
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: print-version
          image: ghcr.io/gihyodocker/print-version:v0.0.1
          livenessProbe:
            exec:
              command:
                - cat
                - /var/tmp/live.txt # 存在しないのでunhealtyになる
            # tcpSocket:
            #   port: 80
            initialDelaySeconds: 5
            # timeoutSeconds: 5
            # successThreshold: 1
            # failureThreshold: 3
            periodSeconds: 10
          readinessProbe: # httpサーバが立ち上がったことを確認する
            httpGet:
              path: /hc
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            # successThreshold: 1
            # failureThreshold: 3
            # periodSeconds: 10
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: print-version
                  key: DB_HOST
          ports:
            - containerPort: 80
              name: print-version
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Taipei
      restartPolicy: Always
---
